@startuml
'https://plantuml.com/class-diagram

interface Iterable<String>{
}

interface ExpressionRepository {
    void loadFromFile(String fileName)
    String getNextExpression()
}

ExpressionRepository --|>Iterable

class SetExpressionParser implements ExpressionParser{
    -String normalize(String source)
    +void execute(String source)
}


class PrintExpressionParser implements ExpressionParser{
    +void execute(String source)
}

interface ExpressionParser{
    void execute(String source)
}

class ScriptRepo implements ExpressionRepository{
    +void loadFromFile(String fileName)
    +String getNextExpression()
}

class ScriptParser {
    -ExpressionRepository source
    -VariablesRepository context
    -Map<ExpressionType, ExpressionParser> executors
    -OutputStream result
    +registerExecutor(ExpressionParser executor)
    +executeAll()
}

ScriptParser..>ExpressionType
ScriptParser..>ExpressionParser
ScriptParser..> ExpressionRepository
ScriptParser ..>VariablesRepository

interface VariablesRepository{
    putValue(..)
    getValue(..)
}

class EvaluationContext implements VariablesRepository{
    +putValue(..)
    +getValue(..)
}

enum OperatorType{
    SUM
    SUB
    MUL
    DIV
}

enum ExpressionType{
    SET
    PRINT
    COMMENT
}


@enduml